from setuptools import setup, find_packages

setup(
    name="jarvis-tui",
    version="0.1.0",
    description="JARVIS-like terminal TUI agent with local AI",
    readme="README.md",
    python_requires=">=3.10",
    packages=find_packages(where="."),
    include_package_data=True,
    install_requires=[
        "textual>=0.52",
        "ollama>=0.3",
        "mcp>=1.0",
        "chromadb>=0.5",
        "sentence-transformers>=3.0",
        "sounddevice>=0.4",
        "numpy>=1.26",
        "psutil>=5.9",
        "platformdirs>=4.0",
        "pyyaml>=6.0",
        "pydantic>=2.7",
        "pydantic-settings>=2.3",
        "rich>=13.7",
        "httpx>=0.27",
        "python-dotenv>=1.0",
        "duckduckgo-search>=6.0",
        "aiohttp>=3.9",
        "playwright>=1.40",
        "pyautogui>=0.9.54",
    ],
    extras_require={
        "offline": [
            "llama-cpp-python>=0.2",
            "openwakeword>=0.6",
            "piper-tts>=1.2",
            "pywhispercpp>=0.6",
            "vosk>=0.3",
            "pvporcupine>=3.0",
        ],
        "llama_cpp": ["llama-cpp-python>=0.2"],
        "voice": [
            "pvporcupine>=3.0",
            "piper-tts>=1.2",
            "openwakeword>=0.6",
            "pywhispercpp>=0.6",
            "vosk>=0.3",
        ],
        "dev": ["pytest", "pytest-asyncio", "textual-dev", "ruff", "mypy"],
        "all": [
            "llama-cpp-python>=0.2",
            "pvporcupine>=3.0",
            "openwakeword>=0.6",
            "piper-tts>=1.2",
            "pywhispercpp>=0.6",
            "vosk>=0.3",
        ],
    },
    entry_points={
        "console_scripts": [
            "jarvis=jarvis.main:main",
            "jarvis-mcp-filesystem=jarvis.mcp.servers.filesystem:main",
            "jarvis-mcp-terminal=jarvis.mcp.servers.terminal:main",
            "jarvis-mcp-git=jarvis.mcp.servers.git:main",
            "jarvis-mcp-memory=jarvis.mcp.servers.memory:main",
            "jarvis-mcp-web-search=jarvis.mcp.servers.web_search:main",
            "jarvis-mcp-browser=jarvis.mcp.servers.browser:main",
            "jarvis-mcp-desktop=jarvis.mcp.servers.desktop:main",
        ],
    },
)
